<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto1)>
    <!ATTLIST agenda xml:lang CDATA #REQUIRED>

    <!ELEMENT contacto1 (nombre, apellido, empresa, puestoTrabajo, mail, telf, direccion, fechaNacimiento)>

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT empresa (#PCDATA)>
    <!ELEMENT puestoTrabajo (#PCDATA)>
    <!ELEMENT mail (#PCDATA)>
    <!ELEMENT telf (#PCDATA)>

    <!ELEMENT direccion (pais, calle, ciudad, provincia, codigoPostal)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT codigoPostal (#PCDATA)>

    <!ELEMENT fechaNacimiento (dia, mes, anio)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
]>

<agenda xml:lang="es">
    <contacto1>
        <nombre>Lexico</nombre>
        <apellido>Abe</apellido>
        <empresa>Digitech</empresa>
        <puestoTrabajo>Estudiante</puestoTrabajo>
        <mail>teralex142@gmail.com</mail>
        <telf>+34 123456789</telf>


        <direccion>
            <pais>España</pais>
            <calle>Diputació</calle>
            <ciudad>Barcelona</ciudad>
            <provincia>Barcelona</provincia>
            <codigoPostal>08015</codigoPostal>
        </direccion>

        <fechaNacimiento>
            <dia>24</dia>
            <mes>2</mes>
            <anio>2007</anio>
        </fechaNacimiento>
    </contacto1>
</agenda>